addr: 0.0.0.0:8080
llm:
- api_key: API-KEY
  base_url: https://api.vveai.com/v1 
  model: gpt-4.1 
  provider: openai
  semaphore: 200 
- api_key: sk-sbadfsaf
  base_url: https://api.vveai.com/v1 # LLM base URL, used for VLLM
  model: cc-3-7-sonnet-20250219
  provider: openai 
  semaphore: 200 
- api_key: API-KEY
  base_url: https://api.vveai.com/v1 
  model: deepseek-chat
  provider: openai
  semaphore: 200 
- api_key: sk-sbadfsaf
  base_url: https://api.vveai.com/v1 # LLM base URL, used for VLLM
  model: qwen-plus
  provider: openai 
  semaphore: 200 
env:
  avro:
    enabled: false # Whether to enable Avro
    path: <AVRO-OUTPUT-PATH> # Path to the Avro output file
  mlflow:
    enabled: true # Whether to enable MLflow
    mlflow_uri: http://localhost:59000 # MLflow server URI
    username: admin # MLflow server username
    password: CHANGE_ME # MLflow server password
  pgsql:
    enabled: true # Whether to enable PostgreSQL
    dsn: postgresql://postgres:CHANGE_ME@localhost:5432/postgres # PostgreSQL connection string
  redis:
    server: localhost # Redis server address
    port: 6379 # Redis port
    password: CHANGE_ME # Redis password
map:
  file_path: "./data/beijing_map.pb" # Path to the map file
  # cache_path: ./data/beijing_map.pb # Cache path for accelerating map file loading
agents:
  citizens:
  - agent_class: citizen # The class of the agent
    number: 1 # The number of the agents
  firms:
  - agent_class: firm
    number: 16
  goverment:
  - agent_class: goverment
    number: 1
exp:
  name: enterprise-simulation # Experiment name
  environment:
    start_tick: 28800 # Start time in seconds
    total_tick: 7200 # Total time in seconds
  workflow:
  - day: 4 # The day of the workflow step
    type: run # The type of the workflow step
