services:
  mlflow-svc:
    # because Docker Desktop cannot attach folders in WSL2, we need to build the image locally
    build:
      context: ./mlflow
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: bitnamilegacy/mlflow:2.19.0
    container_name: mlflow
    restart: always
    ports:
      - 59000:59000
    volumes:
      - mlflow:/app
    environment:
      MLFLOW_AUTH_CONFIG_PATH: /mlflow/basic_auth.ini
      POSTGRESQL_PASSWORD: SupplyChainDB2026
    depends_on:
      - postgresql-svc

  postgresql-svc:
    image: bitnami/postgresql:latest
    container_name: postgresql
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/bitnami/postgresql
    environment:
      POSTGRESQL_PASSWORD: CHANGE_ME

  redis-svc:
    image: bitnami/redis:latest
    container_name: redis 
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "SupplyChainRedis2026", "ping"]
      interval: 5s
      timeout: 30s
      retries: 3
    restart: always
    environment:
      REDIS_PASSWORD: SupplyChainRedis2026
      REDIS_AOF_ENABLED: no
    ports:
      - 6379:6379 # TCP Listener for Redis
      # - 26379:26379 # TCP Listener for Redis Sentinel
      # - 6380:6380 # TCP Listener for Redis (Cluster)
      

volumes:
  mlflow:
  postgresql:
