import React from 'react';
import { Tag, Tooltip } from 'antd';
import { CheckCircleOutlined, InfoCircleOutlined, WarningOutlined, ExperimentOutlined } from '@ant-design/icons';
import { DataProvenance } from '../../services/controlTowerApi';

interface ProvenanceBadgeProps {
  provenance: DataProvenance | 'SIMULATED';
  sourceNote?: string;
  size?: 'small' | 'default';
}

export const ProvenanceBadge: React.FC<ProvenanceBadgeProps> = ({
  provenance,
  sourceNote,
  size = 'default',
}) => {
  let color = 'default';
  let icon = <InfoCircleOutlined />;
  let label = 'DATA UNKNOWN';
  let defaultNote = 'Data origin unverified';

  switch (provenance) {
    case 'LIVE':
      color = 'success';
      icon = <CheckCircleOutlined />;
      label = 'LIVE BACKEND';
      defaultNote = 'Verified live data from PostgreSQL / Neo4j persistence.';
      break;
    case 'DEMO':
      color = 'processing';
      icon = <InfoCircleOutlined />;
      label = 'DEMO DATA';
      defaultNote = 'Simulated operational dataset loaded for evaluation.';
      break;
    case 'FALLBACK':
      color = 'warning';
      icon = <WarningOutlined />;
      label = 'OFFLINE FALLBACK';
      defaultNote = 'Backend service offline or unconfigured. Certified local fallback data displayed.';
      break;
    case 'SIMULATED':
      color = 'purple';
      icon = <ExperimentOutlined />;
      label = 'AI SIMULATION';
      defaultNote = 'Generated by agent simulation / heuristic model. Not a real-world prediction.';
      break;
  }

  const tagContent = (
    <Tag
      color={color}
      icon={icon}
      style={{
        fontWeight: 600,
        letterSpacing: '0.04em',
        padding: size === 'small' ? '0 6px' : '2px 8px',
        fontSize: size === 'small' ? '11px' : '12px',
        borderRadius: '4px',
      }}
    >
      {label}
    </Tag>
  );

  return (
    <Tooltip title={sourceNote || defaultNote} placement="bottom">
      {tagContent}
    </Tooltip>
  );
};

export default ProvenanceBadge;
